In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('./case_study_validation_data.csv')
df

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,target,cat_feature_1,cat_feature_2
0,28.767169,161.966498,81.872549,99.835205,269.739988,203.647127,249.435960,117.578044,127.856154,111.061091,126.024153,177.980983,152.021918,319.135333,140.016792,112.977020,High,Category_A
1,218.938143,119.791942,167.343711,193.325205,-79.015534,53.199300,146.831591,122.634255,73.221506,79.423254,110.618714,-23.065378,133.769639,273.784216,60.854829,105.844625,Low,Category_A
2,73.635323,221.318585,99.913021,-22.305286,228.404987,111.664161,257.811522,59.378286,61.426489,86.798618,45.785137,78.697077,196.370792,-2.577077,-22.645914,93.708970,Low,Category_B
3,254.599403,9.245377,151.656239,93.377091,-31.668459,92.511416,198.598885,66.328654,232.164797,215.983485,192.334588,266.697438,147.023177,170.750747,105.240839,115.455498,Low,Category_A
4,290.040861,161.374547,70.177088,74.350879,230.188671,230.777534,251.258058,183.337692,240.107252,278.940438,183.484400,137.560854,169.524114,172.233807,0.996204,187.083308,High,Category_C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,5.137600,223.650110,262.706014,34.115822,56.149873,203.199104,23.526109,10.265990,125.915993,174.469443,206.620790,8.447183,8.799652,62.261204,199.040973,111.933168,Low,Category_A
99996,-24.785508,54.086621,253.093477,140.302047,66.938113,113.096096,79.655440,112.177999,35.849802,187.404075,-29.669458,-29.467787,151.939305,111.344186,-19.787619,98.208574,Low,Category_A
99997,95.691137,-60.539674,182.792261,124.955195,129.011832,73.903342,72.483219,72.410532,223.346991,118.818122,-40.974059,5.113943,63.857116,142.451584,230.030930,102.714185,High,Category_A
99998,-15.557983,212.114566,-33.215685,108.988587,211.905884,291.579619,353.093819,149.118057,-23.918542,19.985540,-129.389272,154.531081,175.965241,108.808665,272.826414,91.244749,Low,Category_A
99999,228.476620,121.324249,328.229965,257.140130,150.158028,163.996202,181.255538,242.381308,297.442216,271.180491,149.623438,351.293947,275.057575,251.957609,335.923949,218.138541,Low,Category_C

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error

# Read 1  the CSV file into a DataFrame
df = pd.read_csv('case_study_validation_data.csv')

# Convert all column names to strings
df.columns = df.columns.astype(str)

# Create a OneHotEncoder object
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the columns cat_feature_1 and cat_feature_2
encoder.fit(df[['cat_feature_1', 'cat_feature_2']])

# Transform the columns cat_feature_1 and cat_feature_2
encoded_features = encoder.transform(df[['cat_feature_1', 'cat_feature_2']])

# Get the feature names from the encoder
encoded_feature_names = encoder.get_feature_names_out(['cat_feature_1', 'cat_feature_2'])

# Create a new DataFrame by concatenating the existing DataFrame with the encoded features
df_encoded = pd.concat([df, pd.DataFrame(encoded_features, columns=encoded_feature_names)], axis=1).drop(['cat_feature_1', 'cat_feature_2'], axis=1)

# Split the data into training and testing sets
X = df_encoded.drop('target', axis=1)
y = df_encoded['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on the testing set
y_pred = model.predict(X_test)

# Evaluate the model using the RMSE metric
rmse = mean_squared_error(y_test, y_pred, squared=False)

# Print the RMSE score
print(f'RMSE: {rmse}')

RMSE: 18.575778038383778

/Users/k1r1m1/dev/sunking/ds_hackathon/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [9]:
import pickle

In [10]:
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)